# Generated by Django 4.1.5 on 2023-01-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(max_length=50)),
                ("transmission", models.CharField(max_length=50)),
                ("doors", models.IntegerField()),
                ("seats", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("gas_type", models.CharField(max_length=50)),
                ("revisions", models.BooleanField(default=False)),
                ("last_maintance", models.DateField(null=True)),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
