# Generated by Django 4.1.5 on 2023-01-06 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicleorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicleorder",
            name="owner",
        ),
        migrations.AddField(
            model_name="vehicleorder",
            name="vehicle",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.vehicle",
            ),
            preserve_default=False,
        ),
    ]
