# Generated by Django 4.1.5 on 2023-01-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0006_remove_vehicleorder_vehicle_vehicleorder_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleorder",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_order",
                to="vehicles.vehicle",
            ),
        ),
    ]
